import Image from 'next/image'
import { ArrowDownRight, HeartHandshake, Home as HomeIcon, Leaf, Mountain, Sprout, Users, Waves } from 'lucide-react'
import { ArrowLink, ButtonLink, ContactSection, FeatureBand, Footer, HeritageVisual, HeroImage, ImageCard, ImpactItem, PillarIcon, SectionLabel, SectionTitle, SiteHeader, Stat } from '@/components/site-header'
import { LeaderCard } from '@/components/leader-card'
import { leaderData } from '@/lib/leadership-data'
import { ScrollToHash } from '@/components/scroll-to-hash'

const pillarData = [['Environment','Protecting our river, mangroves, natural resources, and surrounding ecosystems.'],['Culture & Heritage','Preserving Putiao identity, traditions, foods, crafts, fishing heritage, and community stories.'],['Sustainable Tourism','Promoting responsible community-based tourism that protects nature and benefits local residents.'],['Livelihood & Community Development','Creating opportunities for sustainable and inclusive local growth.'],['Community Service','Serving residents, strengthening relationships, and helping the community during times of need.']] as const
const updateData = [['River stewardship','Small actions, shared responsibility','A cleaner river begins with neighbors showing up for the place we call home.'],['Culture & heritage','Keeping local stories alive','From food and fishing to crafts and traditions, Putiao identity is worth carrying forward.'],['Community service','Standing with our community','When hardship comes, volunteers and resources move together to help families in need.']] as const

export default function Home() {
  return <div id="top" className="min-h-screen bg-[#fafcfa]">
    <ScrollToHash />
    <SiteHeader />
    <main>
      <section className="mx-auto max-w-[1240px] px-5 pb-20 pt-12 sm:px-8 sm:pt-20 lg:pb-28"><div className="grid items-center gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:gap-20"><div><SectionLabel>A cleaner river. A stronger community.</SectionLabel><h1 className="max-w-xl text-5xl font-extrabold leading-[0.98] tracking-[-0.07em] text-[#10221b] sm:text-6xl lg:text-[76px]">Putiao, my place,<br /><span className="text-[#0b6b3a]">my home.</span></h1><p className="mt-7 max-w-lg text-base leading-7 text-[#66736d]">Protecting the Putiao River, preserving our culture and heritage, supporting livelihoods, and building a stronger, united community for a sustainable tomorrow.</p><p className="mt-5 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.12em] text-[#45554e]"><span className="size-2 rounded-full bg-[#4daa31]" />Putiao, Pilar 4714, Sorsogon</p><div className="mt-8 flex flex-wrap gap-3"><ButtonLink>Get involved</ButtonLink><ButtonLink href="/#about" secondary>Learn more <ArrowDownRight className="ml-2 size-4" /></ButtonLink></div><div className="mt-12 grid max-w-md grid-cols-3 gap-6 border-t border-[#dfe9e2] pt-6"><Stat value="200+" label="Members and volunteers, and counting" /><Stat value="Est. '24" label="A growing community for lasting change" /><Stat value="5 pillars" label="One shared vision for Putiao" /></div></div><HeroImage /></div></section>
      <section className="mx-auto max-w-[1240px] px-5 pb-20 sm:px-8"><FeatureBand /></section>
      <section className="scroll-mt-28 border-y border-[#e5eee7] bg-white" id="about"><div className="mx-auto grid max-w-[1240px] gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[0.85fr_1.15fr] lg:gap-24 lg:py-28"><div><SectionLabel>Our purpose</SectionLabel><div className="mb-5 flex items-center gap-3"><Image src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/cso_logo-Dr5hyzQPKbFCclISUSc4rVP6BZ720g.png" alt="Putiao organization logo" width={56} height={56} className="size-14 rounded-full object-cover" /><span className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#0b6b3a]">Est. 2024</span></div><h2 className="max-w-md text-4xl font-extrabold tracking-[-0.05em] text-[#10221b] sm:text-5xl">Rooted in place. Moving forward together.</h2><p className="mt-5 max-w-md text-sm leading-7 text-[#66736d]">PMPMH is a non-partisan, non-political, community-based civil society organization working with the people of Putiao and surrounding communities.</p><ArrowLink href="/#about">Learn about our story</ArrowLink></div><div className="grid gap-4 sm:grid-cols-2"><article className="rounded-[22px] bg-[#eff8f2] p-7"><span className="grid size-11 place-items-center rounded-2xl bg-white text-[#0b6b3a]"><Sprout className="size-5" /></span><h3 className="mt-8 text-2xl font-extrabold tracking-tight text-[#10221b]">Our mission</h3><p className="mt-3 text-sm leading-6 text-[#66736d]">To protect and conserve the Putiao River, preserve our culture and heritage, support sustainable livelihoods, and build a united and resilient community.</p></article><article className="rounded-[22px] bg-[#10221b] p-7 text-white"><span className="grid size-11 place-items-center rounded-2xl bg-white/10 text-[#b4e69e]"><Mountain className="size-5" /></span><h3 className="mt-8 text-2xl font-extrabold tracking-tight">Our vision</h3><p className="mt-3 text-sm leading-6 text-white/60">A vibrant and sustainable Putiao where a healthy river, rich culture, and empowered community create opportunities for generations to come.</p></article></div></div></section>
      <section className="scroll-mt-28 mx-auto max-w-[1240px] px-5 py-20 sm:px-8 lg:py-28" id="programs"><SectionTitle eyebrow="What we do" title="Five ways we show up for Putiao." /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{pillarData.map(([title, text], index) => <div key={title} className="flex flex-col gap-5 rounded-[20px] border border-[#dfe9e2] bg-white p-5"><PillarIcon icon={[Leaf, HomeIcon, Waves, Users, HeartHandshake][index]} /><div><h3 className="font-extrabold text-[#10221b]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#66736d]">{text}</p></div></div>)}</div></section>
      <section className="bg-[#eff8f2]"><div className="mx-auto max-w-[1240px] px-5 py-20 sm:px-8 lg:py-28"><SectionTitle eyebrow="Programs in action" title="Our work in the community"><ArrowLink href="/#updates">View all updates</ArrowLink></SectionTitle><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4"><ImageCard title="Putiao River Clean-up" text="Environmental stewardship, river conservation, volunteer participation, and cleaner surroundings." imageClass="bg-[url('/putiao-river.png')] bg-cover bg-center" /><ImageCard title="Culture & Heritage" text="Reviving local foods, fishing traditions, handicraft making, and community heritage." imageClass="bg-[#bddbbf]" /><ImageCard title="Community Outreach" text="Standing with residents through assistance, relief operations, and shared care." imageClass="bg-[#a9cbb1]" /><ImageCard title="Putiao River Cruise" text="An eco-tourism initiative currently in development. Building an initial cruiser designed for approximately eight tourists per trip." imageClass="bg-[#8ebba0]" /></div></div></section>
      <section className="mx-auto grid max-w-[1240px] gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-center lg:py-28"><HeritageVisual /><div><SectionLabel>Culture & heritage</SectionLabel><h2 className="text-4xl font-extrabold tracking-[-0.05em] text-[#10221b] sm:text-5xl">A place is made of stories.</h2><p className="mt-5 text-sm leading-7 text-[#66736d]">Putiao’s river-based life is held in its local foods, fishing traditions, handmade crafts, livelihoods, and the stories shared across generations.</p><p className="mt-4 text-sm leading-7 text-[#66736d]">We are building a living digital archive of the heritage that gives this community its identity.</p><div className="mt-7"><ArrowLink href="/#contact-form">Share a Putiao story</ArrowLink></div></div></section>
      <section className="scroll-mt-28 bg-[#f5f8f5]" id="leadership"><div className="mx-auto max-w-[1240px] px-5 py-20 sm:px-8 lg:py-28"><SectionTitle eyebrow="Our leadership" title="The people behind the work." /><p className="mt-5 max-w-2xl text-sm leading-7 text-[#66736d]">PMPMH is guided by a Board of Directors committed to community-led development, environmental responsibility, and a sustainable future for Putiao.</p><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{leaderData.map((leader) => <LeaderCard key={leader.name} leader={leader} />)}</div></div></section>
      <section className="mx-auto max-w-[1240px] px-5 py-20 sm:px-8 lg:py-28"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-end"><div><SectionLabel>Our shared impact</SectionLabel><h2 className="text-4xl font-extrabold tracking-[-0.05em] text-[#10221b] sm:text-5xl">Building a better Putiao, together.</h2><p className="mt-5 text-sm leading-7 text-[#66736d]">The work is ongoing, and every contribution helps move the community forward.</p></div><div className="grid gap-6 sm:grid-cols-2"><ImpactItem title="200+" text="Members and volunteers and counting" /><ImpactItem title="Cleaner River" text="Environmental stewardship" /><ImpactItem title="Preserved Heritage" text="Culture and traditions" /><ImpactItem title="United Community" text="A shared future" /></div></div></section>
      <section className="scroll-mt-28 bg-[#eff8f2]" id="updates"><div className="mx-auto max-w-[1240px] px-5 py-20 sm:px-8 lg:py-28"><SectionTitle eyebrow="Community stories" title="What’s happening in Putiao."><ArrowLink href="/#updates">View all updates</ArrowLink></SectionTitle><div className="mt-10 grid gap-5 md:grid-cols-3">{updateData.map(([tag, title, text], i) => <article key={title} className="overflow-hidden rounded-[22px] border border-[#d7e8dc] bg-white"><div className={`h-3 ${i === 0 ? 'bg-[#4daa31]' : i === 1 ? 'bg-[#0b6b3a]' : 'bg-[#8ebba0]'}`} /><div className="p-6"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#0b6b3a]">{tag}</p><h3 className="mt-4 text-2xl font-extrabold tracking-tight text-[#10221b]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#66736d]">{text}</p><p className="mt-6 text-xs italic text-[#91a097]">Story details coming soon</p></div></article>)}</div></div></section>
      <ContactSection />
    </main>
    <Footer />
  </div>
}

export const dynamic = 'force-static'

export const metadata = { title: 'Putiao, My Place, My Home, CSO, Inc.' }

export function HeroImagePlaceholder() { return <Image src="/putiao-river.png" alt="Putiao River" width={1200} height={800} /> }

export const unused = [ArrowDownRight]
